//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestsManagementService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestWorks
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        public int WorkId { get; set; }
        public int UserId { get; set; }
        public decimal Price { get; set; }
    
        public virtual Requests Requests { get; set; }
        public virtual Users Users { get; set; }
        public virtual Work Work { get; set; }
    }
}
