//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestsManagementService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RequestsManagementEntities : DbContext
    {
        private static RequestsManagementEntities _data;

        public RequestsManagementEntities()
            : base("name=RequestsManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static RequestsManagementEntities GetContext()
        {
            if (_data == null)
            {
                _data = new RequestsManagementEntities();
            }
            return _data;
        }

        public virtual DbSet<ExecutionRequests> ExecutionRequests { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<RequestMaterials> RequestMaterials { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<RequestWorks> RequestWorks { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Work> Work { get; set; }
    }
}
