//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestsManagementService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.ExecutionRequests = new HashSet<ExecutionRequests>();
            this.RequestMaterials = new HashSet<RequestMaterials>();
            this.RequestWorks = new HashSet<RequestWorks>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Equipment { get; set; }
        public string Malfunction { get; set; }
        public string IssueDescription { get; set; }
        public string UserDescription { get; set; }
        public System.DateTime ExpectedCompletionDate { get; set; }
        public System.TimeSpan ExpectedCompletionTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecutionRequests> ExecutionRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestMaterials> RequestMaterials { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestWorks> RequestWorks { get; set; }
    }
}
